name: my_sports_tracker
description: "A new Flutter project for sports tracking."

publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  ui_utility_package:
    path: ../packages/ui_utility_package
  flutter_bloc:
  equatable:
  shared_preferences:
  cupertino_icons: ^1.0.8
  intl:
  screenshot:
  path_provider:
  share_plus:
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true